//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace slnShopping.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;
    public partial class tGusetBooks
    {
        
        public int fId { get; set; }

        [DisplayName("姓名")]
        [Required]
        public string fName { get; set; }

        [DisplayName("留言")]
        [Required]
        public string fContent { get; set; }

        [DisplayName("新增時間")]
        [Required]
        public System.DateTime fCreateTime { get; set; }

        [DisplayName("回覆留言")]
        [Required]
        public string fReply { get; set; }

        [DisplayName("回覆時間")]
        [Required]
        public Nullable<System.DateTime> fReplyTime { get; set; }
    }
}
