//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace slnShopping.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;
    public partial class tMember
    {

        public int fId { get; set; }

        [DisplayName("帳號")]
        [Required]
        [StringLength(12,ErrorMessage ="帳號必須要3-12個字元",MinimumLength =3)]
        public string fUserId { get; set; }

        [DisplayName("密碼")]
        [Required]
        [StringLength(12,ErrorMessage ="密碼必須為6-12個字元",MinimumLength =6)]
        public string fPwd { get; set; }

        [DisplayName("姓名")]
        [Required]
        public string fName { get; set; }

        [DisplayName("信箱")]
        [Required]
        [EmailAddress]
        public string fEmail { get; set; }
    }
}
